#!/bin/bash
#Load data in three times

cd /data/raw
export LD_LIBRARY_PATH=/usr/local/lib
#Load three copies
for f in *.txt; do ~/BigAggBlog/fastload $f; done
for f in *.txt; do ~/BigAggBlog/fastload $f; done
for f in *.txt; do ~/BigAggBlog/fastload $f; done


